import { chromium } from '@playwright/test'
const out = process.argv[2]
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } })
await page.goto('http://127.0.0.1:1420/')
const canvas = page.getByTestId('canvas-viewport')
const box = await canvas.boundingBox()
const drag = async (a, b) => {
  await page.mouse.move(box.x + a[0], box.y + a[1])
  await page.mouse.down()
  await page.mouse.move(box.x + b[0], box.y + b[1], { steps: 6 })
  await page.mouse.up()
}
await page.keyboard.press('f')
await drag([120, 120], [620, 400])
await page.keyboard.press('f')
await drag([700, 450], [1050, 700])
await page.keyboard.press('r')
await drag([160, 170], [360, 280])
await page.keyboard.press('o')
await drag([400, 170], [580, 300])
await page.keyboard.press('d')
await drag([740, 500], [900, 620])
await page.keyboard.press('t')
await canvas.click({ position: { x: 170, y: 320 } })
await page.keyboard.type('Quarterly roadmap — smooth zoom between frames')
await page.keyboard.press('Escape')
await page
  .locator('[data-element-type="shape"]')
  .first()
  .click({ position: { x: 5, y: 5 }, force: true })
await page.mouse.click(box.x + 200, box.y + 200)
await page.screenshot({ path: `${out}/editor.png` })
await page.getByRole('button', { name: 'Present', exact: true }).click()
await page.waitForTimeout(1300)
await page.screenshot({ path: `${out}/present.png` })
await browser.close()
